language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
install: npm install && npm install --save-dev && npm install grunt-haxe && npm install grunt-zip && npm install grunt-exec
before_script: grunt
